name: Continuous Delivery

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build-n-publish:
    name: PyPI and TestPyPI Deployment
    runs-on: ubuntu-latest
    container:
      image: python

    steps:
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Build a binary wheel and source tarball
        run: pipenv run python setup.py sdist bdist_wheel

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
